# Default values for restaurant-svc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Kitchen Service 版本定义列表
# Helm Chart 将为列表中的每一项创建一个独立的 Deployment
kitchenServiceVersions:
  - version: "v0"                  # 版本标识，将用作 version 标签的值
    replicaCount: 1                # v0 版本的副本数
    #deploymentNameSuffix: "-v0"   # 用于生成唯一的 Deployment 名称后缀 (例如 myrelease-kitchensvc-v0)
    # imageTag: {{ .Values.image.kitchenSvc.tag }} # 使用顶层定义的 kitchenSvc tag 作为 v0 的默认值
                                                 # 如果需要，可以在这里为 v0 指定不同的 tag
    # resources: {}                              # 可选：如果 v0 需要特定资源配置，在这里覆盖顶层 kitchenSvc 资源
  - version: "v1"
    replicaCount: 1
    # deploymentNameSuffix: "-v1"
    # imageTag: "kitchen-service-new-tag"      # 可选：如果 v1 使用特定 tag
    # resources: {}    

#DONE implement docker repo and tags for the 2 services. In our lab, you need to put the 2 service
#DONE images to the same repo, and distinguish them using tags.
image:
  repository: oonulven/nullius
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  restaurantSvc:
    tag: restaurant-service.1.5
  kitchenSvc:
    tag: kitchen-service.1.5

imagePullSecrets: 
  - name: regcred

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # DONE implement proper service type and port here for the 2 services.
  restaurantSvc:
    type: ClusterIP
    port: 8763
    targetPort: 8763
  kitchenSvc:
    type: ClusterIP
    port: 8764
    targetPort: 8764



resources:
  #DONE define proper hardware resource manifest for the 2 services. Your implementation should contain
  #DONE 'requests' and 'limits' for both CPU and memory. Design them so that your app can run smoothly.
  restaurantSvc:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  kitchenSvc:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
