apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-restaurantsvcapp
  labels:
    app: restaurantsvc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: restaurantsvc
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        #DONE define proper label/labels for pod template.
        app: restaurantsvc
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "restaurant-svc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: restaurantsvcapp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          #DONE implement image path by repo and tag, from Values.yaml
          image: "{{ .Values.image.repository }}:{{ .Values.image.restaurantSvc.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #DONE implement proper port, readiness and liveness probes here.
          #DONE please provide a reasonable initialDelaySeconds here. You can try firstly remove it and see
          #DONE what will happen per you app.
          ports:
            - name: http
              containerPort: {{ .Values.service.restaurantSvc.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 5
          resources:
          #DONE define proper hardware resources here. Leverage resources definition
          #DONE in Values.yaml
            {{- toYaml .Values.resources.restaurantSvc | nindent 12 }}
