{{- if .Values.installKitchensvcResillience -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-destination-rule-kitchensvc
spec:
  host: restaurantsvc-kitchensvc
  subsets:
    - name: v0
    # DONE fill in proper label selector here
      labels:
        version: v0
    - name: v1
    # DONE fill in proper label selector here
      labels:
        version: v1
      #DONE fill in `trafficPolicy` conf here
      trafficPolicy:
        connectionPool:
          tcp:
            maxConnections: 1
            connectTimeout: 10ms
          http:
            http1MaxPendingRequests: 1
            maxRequestsPerConnection: 1
    # outlierDetection:
    #   consecutive5xxErrors: 1
    #   interval: 1s
    #   baseEjectionTime: 60s
    #   maxEjectionPercent: 100
{{- end -}}
